remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: [true]
title: [luogu vs codeforces]
description: [codeforces for sure]
github:
  zip_url: https://github.com/RainPPR/luogu-vs-codeforces/zipball/main
  tar_url: https://github.com/RainPPR/luogu-vs-codeforces/tarball/main
